import Image from "next/image";
import Head from "next/head";
import Header from "./composant/Header";
import Footer from "./composant/Footer";


export default function Home() {
  return (
    <>
          <Head>
            <title>Gestion de position</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
        <div>
            <Header />

            <div className="body">
        <br />
        <h1 className="font-bold text-3xl">Bienvenu dans notre site</h1>
        <br />
        <p>
          Lorem ipsum dolor sit amet consectetur, adipisicing elit.
           Sapiente officia quia molestias minima inventore pariatur.
           Quod culpa necessitatibus deleniti illo labore nam ex, omnis 
           cum voluptatum! Aspernatur corrupti exercitationem perspiciatis?
           Lorem ipsum dolor sit amet consectetur, adipisicing elit.
           Sapiente officia quia molestias minima inventore pariatur.
           Quod culpa necessitatibus deleniti illo labore nam ex, omnis 
           cum voluptatum! Aspernatur corrupti exercitationem perspiciatis?
           Lorem ipsum dolor sit amet consectetur, adipisicing elit.
           Sapiente officia quia molestias minima inventore pariatur.
           Quod culpa necessitatibus deleniti illo labore nam ex, omnis 
           cum voluptatum! Aspernatur corrupti exercitationem perspiciatis?
        </p>
      </div>

            <Footer />
        </div>
    </>
  );
}
